language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t pavneshkaushal/frontend-complex-client-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true pavneshkaushal/frontend-complex-client-test npm run test

after_success:
  - docker build -t pavneshkaushal/frontend-complex-client ./client .
  - docker build -t pavneshkaushal/frontend-complex-server ./server .
  - docker build -t pavneshkaushal/frontend-complex-worker ./worker .
  - docker build -t pavneshkaushal/frontend-complex-nginx  ./nginx .
  

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend2"
  env: "Frontend2-env"
  bucket_name: "elasticbeanstalk-us-east-2-836200856165"
  bucket_path: "frontend2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"