language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t panak4572/frontend-complex-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true panak4572/frontend-complex-client-test npm run test

after_success:
  - docker build -t panak4572/frontend-complex-client ./client
  - docker build -t panak4572/frontend-complex-server ./server
  - docker build -t panak4572/frontend-complex-worker ./worker
  - docker build -t panak4572/frontend-complex-nginx  ./nginx
  # login to DOCKER CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push panak4572/frontend-complex-client
  - docker push panak4572/frontend-complex-server
  - docker push panak4572/frontend-complex-worker
  - docker push panak4572/frontend-complex-nginx

  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend-complex-multi-docker"
  env: "Frontend-complex-multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-836200856165"  
  bucket_path: "frontend-complex-multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
